/* SICIP v5.19.5 PWA instalable + alertas locales + actualización */
(function(){
  'use strict';
  var VERSION='5.19.6-auto-update';
  var CHECK_MS=60000;
  var STORE_LAST='sicip_pwa_last_notification_seen';
  var STORE_INSTALL_HIDE='sicip_pwa_install_hide_until';
  var deferredPrompt=null;
  function $(id){return document.getElementById(id)}
  function getUser(){try{return JSON.parse(sessionStorage.getItem('sicip_usuario')||'null')}catch(e){return null}}
  function userKeys(){var u=getUser()||{};return [u.uid,u.matricula,u.id].filter(Boolean).map(String)}
  function css(){if($('sicip-pwa-style'))return;var s=document.createElement('style');s.id='sicip-pwa-style';s.textContent='\
    .sicip-pwa-card{position:fixed;left:12px;right:12px;bottom:12px;z-index:2147483000;background:#fff;border:1px solid #bbf7d0;border-left:5px solid #005235;border-radius:16px;box-shadow:0 16px 40px rgba(0,0,0,.18);padding:12px 14px;font-family:Inter,Arial,sans-serif;color:#1f2937;display:flex;gap:12px;align-items:center;max-width:520px;margin:0 auto}.sicip-pwa-card b{color:#005235}.sicip-pwa-card p{margin:2px 0 0;font-size:12px;color:#4b5563}.sicip-pwa-card button{border:0;border-radius:999px;padding:9px 12px;font-weight:800;cursor:pointer}.sicip-pwa-primary{background:#005235;color:#fff}.sicip-pwa-secondary{background:#f3f4f6;color:#374151}.sicip-pwa-actions{margin-left:auto;display:flex;gap:8px;flex-wrap:wrap}.sicip-pwa-update{border-color:#99f6e4;border-left-color:#0f766e}.sicip-pwa-update b{color:#0f766e}.sicip-pwa-update .sicip-pwa-primary{background:#0f766e}.sicip-pwa-bell{position:fixed;right:14px;bottom:86px;z-index:2147482999;width:48px;height:48px;border-radius:50%;border:0;background:#005235;color:#fff;box-shadow:0 10px 25px rgba(0,82,53,.35);font-size:20px;cursor:pointer}.sicip-pwa-badge{position:absolute;right:-2px;top:-2px;background:#dc2626;color:#fff;border-radius:999px;font-size:11px;min-width:19px;height:19px;display:flex;align-items:center;justify-content:center;font-weight:900;border:2px solid #fff}.sicip-pwa-toast{position:fixed;top:12px;left:12px;right:12px;z-index:2147483001;background:#064e3b;color:#fff;padding:12px 14px;border-radius:14px;box-shadow:0 10px 30px rgba(0,0,0,.2);font-family:Inter,Arial,sans-serif;max-width:520px;margin:0 auto}.sicip-pwa-toast small{display:block;opacity:.82;margin-top:3px}@media(min-width:720px){.sicip-pwa-card{left:auto;right:18px;bottom:18px}.sicip-pwa-toast{left:auto;right:18px;top:18px}.sicip-pwa-bell{right:22px;bottom:105px}}@media print{.sicip-pwa-card,.sicip-pwa-bell,.sicip-pwa-toast{display:none!important}}\
  ';document.head.appendChild(s)}
  function toast(title,body){css();var old=$('sicip-pwa-toast');if(old)old.remove();var t=document.createElement('div');t.id='sicip-pwa-toast';t.className='sicip-pwa-toast';t.innerHTML='<b>'+escapeHtml(title)+'</b><small>'+escapeHtml(body||'')+'</small>';document.body.appendChild(t);setTimeout(function(){if(t&&t.parentNode)t.remove()},6500)}
  function escapeHtml(s){return String(s||'').replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
  function installHelp(){var ua=navigator.userAgent||'';var isiOS=/iPad|iPhone|iPod/.test(ua)||((navigator.platform||'').indexOf('Mac')>=0&&navigator.maxTouchPoints>1);var isAndroid=/Android/i.test(ua);if(isiOS)return 'En iPhone/iPad: toca Compartir ⬆️ y luego “Agregar a pantalla de inicio”. Apple no permite abrir esa instalación automáticamente.';if(isAndroid)return 'Si no se abrió la instalación automática: abre el menú ⋮ de Chrome y toca “Instalar app” o “Agregar a pantalla principal”.';return 'En este navegador usa el menú del navegador y elige “Instalar app” o “Agregar a pantalla principal”.'}
  function installCard(){css(); if(window.matchMedia('(display-mode: standalone)').matches || window.navigator.standalone) return; var hide=Number(localStorage.getItem(STORE_INSTALL_HIDE)||0); if(Date.now()<hide)return; if($('sicip-pwa-install'))return; var canInstall=!!deferredPrompt; var c=document.createElement('div'); c.id='sicip-pwa-install'; c.className='sicip-pwa-card'; c.innerHTML='<div style="font-size:26px">📲</div><div><b>Instalar SICIP</b><p>'+(canInstall?'Toca Instalar para agregar SICIP como app.':'Tu navegador no abrió instalación automática; toca Ver pasos.')+'</p></div><div class="sicip-pwa-actions"><button class="sicip-pwa-primary" id="sicip-pwa-install-btn">'+(canInstall?'Instalar':'Ver pasos')+'</button><button class="sicip-pwa-secondary" id="sicip-pwa-close-btn">Luego</button></div>'; document.body.appendChild(c); $('sicip-pwa-close-btn').onclick=function(){localStorage.setItem(STORE_INSTALL_HIDE,String(Date.now()+86400000));c.remove()}; $('sicip-pwa-install-btn').onclick=async function(){ if(deferredPrompt){var p=deferredPrompt; deferredPrompt=null; try{p.prompt(); var choice=await p.userChoice; if(choice&&choice.outcome==='accepted'){toast('Instalando SICIP','La app se agregará a tu pantalla de inicio.'); c.remove(); return;} toast('Instalación cancelada','Puedes intentarlo nuevamente desde el aviso o el menú del navegador.');}catch(e){toast('Instalar SICIP',installHelp())} } else {toast('Instalar SICIP',installHelp())}}}
  window.addEventListener('beforeinstallprompt',function(e){e.preventDefault();deferredPrompt=e;setTimeout(installCard,1200)});
  window.addEventListener('appinstalled',function(){toast('SICIP instalado','La app quedó lista en tu pantalla de inicio.')});

  function notificationCard(){css(); if(!('Notification' in window))return; if(Notification.permission!=='default')return; if(!getUser())return; if($('sicip-pwa-notif'))return; var c=document.createElement('div'); c.id='sicip-pwa-notif'; c.className='sicip-pwa-card'; c.style.bottom='86px'; c.innerHTML='<div style="font-size:25px">🔔</div><div><b>Alertas SICIP</b><p>Permite avisos cuando tengas notificaciones nuevas.</p></div><div class="sicip-pwa-actions"><button class="sicip-pwa-primary" id="sicip-pwa-notif-btn">Activar</button><button class="sicip-pwa-secondary" id="sicip-pwa-notif-close">Cerrar</button></div>'; document.body.appendChild(c); $('sicip-pwa-notif-close').onclick=function(){c.remove()}; $('sicip-pwa-notif-btn').onclick=async function(){var ok=await askNotifications(); c.remove(); if(ok){toast('Alertas activadas','Este dispositivo recibirá avisos locales de SICIP.'); check();}}}

  async function askNotifications(){ if(!('Notification' in window)) {toast('Notificaciones no compatibles','Este navegador no permite notificaciones web.'); return false;} if(Notification.permission==='granted') return true; if(Notification.permission==='denied'){toast('Notificaciones bloqueadas','Actívalas desde la configuración del navegador para SICIP.'); return false;} var p=await Notification.requestPermission(); return p==='granted'; }
  async function notify(title,body,url){ try{ if(!await askNotifications()) { toast(title,body); return; } var reg=await navigator.serviceWorker.getRegistration('/'); if(reg&&reg.showNotification){ reg.showNotification(title,{body:body||'',icon:'/icons/sicip-192.png?v=20260614050500',badge:'/icons/sicip-192.png?v=20260614050500',tag:'sicip-notificacion',renotify:true,data:{url:url||'/'}}); } else new Notification(title,{body:body||'',icon:'/icons/sicip-192.png?v=20260614050500'}); }catch(e){toast(title,body)} }
  async function loadNotifications(){var r=await fetch('/data-notificaciones.json?cb='+Date.now(),{cache:'no-store'}); if(!r.ok)return[]; return await r.json();}
  function relevant(list){var keys=userKeys(); if(!keys.length)return[]; return (list||[]).filter(function(n){return n&&!n.leida&&keys.indexOf(String(n.destinatarioMatricula||n.destinatarioUid||n.uid||''))>=0}).sort(function(a,b){return new Date(b.fecha||0)-new Date(a.fecha||0)})}
  function renderBell(count){css();var b=$('sicip-pwa-bell'); if(!count){if(b)b.remove();return} if(!b){b=document.createElement('button');b.id='sicip-pwa-bell';b.className='sicip-pwa-bell';b.title='Notificaciones SICIP';b.innerHTML='🔔<span class="sicip-pwa-badge" id="sicip-pwa-badge"></span>';document.body.appendChild(b);b.onclick=function(){location.hash='/notificaciones';toast('Notificaciones SICIP','Tienes '+(($('sicip-pwa-badge')||{}).textContent||count)+' notificación(es) sin leer.')}} var badge=$('sicip-pwa-badge'); if(badge)badge.textContent=String(count>99?'99+':count)}
  function updateCard(reg){css(); if($('sicip-pwa-update'))return; var c=document.createElement('div'); c.id='sicip-pwa-update'; c.className='sicip-pwa-card sicip-pwa-update'; c.innerHTML='<div style="font-size:25px">↻</div><div><b>Actualización disponible</b><p>Hay una versión nueva de SICIP lista para instalar.</p></div><div class="sicip-pwa-actions"><button class="sicip-pwa-primary" id="sicip-pwa-update-btn">Actualizar</button><button class="sicip-pwa-secondary" id="sicip-pwa-update-close">Luego</button></div>'; document.body.appendChild(c); $('sicip-pwa-update-close').onclick=function(){c.remove()}; $('sicip-pwa-update-btn').onclick=function(){var worker=reg&&(reg.waiting||reg.installing); if(worker)worker.postMessage({type:'SICIP_SKIP_WAITING'}); toast('Actualizando SICIP','La app se recargará con la versión nueva.'); setTimeout(function(){location.reload()},500)}}
  async function checkAppUpdate(){if(!('serviceWorker'in navigator))return; try{var reg=await navigator.serviceWorker.getRegistration('/'); if(!reg)return; if(reg.waiting){updateCard(reg);return} reg.addEventListener('updatefound',function(){var w=reg.installing;if(!w)return;w.addEventListener('statechange',function(){if(w.state==='installed'&&navigator.serviceWorker.controller)updateCard(reg)})}); await reg.update();}catch(e){console.warn('[SICIP PWA] update check',e)}}
  var swReloaded=false;
  var hadSWController=!!navigator.serviceWorker.controller;
  if('serviceWorker'in navigator){
    navigator.serviceWorker.addEventListener('controllerchange',function(){
      if(swReloaded||!hadSWController)return;
      swReloaded=true;
      toast('SICIP actualizado','Recargando con la versión más reciente...');
      setTimeout(function(){location.reload()},800);
    });
    navigator.serviceWorker.addEventListener('message',function(event){
      if(event.data&&event.data.type==='SICIP_SW_UPDATED'){
        if(swReloaded||!hadSWController)return;
        swReloaded=true;
        toast('Nueva versión de SICIP','Recargando con la versión más reciente...');
        setTimeout(function(){location.reload()},1200);
      }
    });
  }
  async function check(){try{var rel=relevant(await loadNotifications()); renderBell(rel.length); if(!rel.length)return; var last=localStorage.getItem(STORE_LAST)||''; var newest=String(rel[0].id||rel[0].fecha||rel[0].mensaje||''); if(newest && newest!==last){localStorage.setItem(STORE_LAST,newest); await notify('Nueva notificación SICIP', rel[0].mensaje||('Tienes '+rel.length+' notificación(es) pendiente(s).'), '/#/notificaciones');}}catch(e){console.warn('[SICIP PWA] notif check',e)}}
  function init(){css(); setTimeout(installCard,2200); setTimeout(notificationCard,4200); setTimeout(checkAppUpdate,1800); setInterval(checkAppUpdate,300000); if('serviceWorker' in navigator){navigator.serviceWorker.ready.then(function(){check(); setInterval(check,CHECK_MS);});} else {check(); setInterval(check,CHECK_MS);} document.addEventListener('visibilitychange',function(){if(!document.hidden){check();checkAppUpdate()}}); window.SICIPPWA={version:VERSION,checkNotifications:check,checkUpdate:checkAppUpdate,enableNotifications:askNotifications,showInstall:installCard,showInstallHelp:function(){toast('Instalar SICIP',installHelp())},showTestNotification:function(){notify('SICIP listo','Las notificaciones están activas en este dispositivo.','/')}}; console.log('[SICIP PWA]',VERSION)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
